-- Sample data for resources
INSERT INTO resources (title, url, category, description, created_at, updated_at)
VALUES ('University Library', 'https://library.university.edu', 'LIBRARY',
        'Main university library with extensive collection', NOW(), NOW()),
       ('Online Catalog', 'https://catalog.library.university.edu', 'LIBRARY', 'Search the library catalog online',
        NOW(), NOW()),
       ('Math Tutoring Center', 'https://math.tutoring.university.edu', 'TUTORING',
        'Free math tutoring for all students', NOW(), NOW()),
       ('Writing Center', 'https://writing.university.edu', 'TUTORING', 'Get help with essays and academic writing',
        NOW(), NOW()),
       ('Student Portal', 'https://portal.university.edu', 'STUDENT_PORTAL',
        'Access grades, schedules, and academic information', NOW(), NOW()),
       ('Course Registration', 'https://registration.university.edu', 'STUDENT_PORTAL', 'Register for courses online',
        NOW(), NOW()),
       ('Academic Advising', 'https://advising.university.edu', 'ACADEMIC_SUPPORT',
        'Schedule appointments with academic advisors', NOW(), NOW()),
       ('Disability Services', 'https://disability.university.edu', 'ACADEMIC_SUPPORT',
        'Support services for students with disabilities', NOW(), NOW()),
       ('Research Database', 'https://research.university.edu', 'RESEARCH', 'Access to academic databases and journals',
        NOW(), NOW()),
       ('Career Services', 'https://career.university.edu', 'CAREER_SERVICES',
        'Resume help, job search, and career counseling', NOW(), NOW()),
       ('Financial Aid Office', 'https://financialaid.university.edu', 'FINANCIAL_AID',
        'Information about scholarships, grants, and loans', NOW(), NOW()),
       ('Health Center', 'https://health.university.edu', 'HEALTH_SERVICES', 'Campus health and wellness services',
        NOW(), NOW());